# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/30697/OneDrive/project_writng/project_writng.runs/synth_1/top_unit_pipelined.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/30697/OneDrive/project_writng/project_writng.cache/wt [current_project]
set_property parent.project_path C:/Users/30697/OneDrive/project_writng/project_writng.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/30697/OneDrive/project_writng/project_writng.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/hdl/PS2Receiver.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/hdl/Seg_7_Display.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/UART/UART_rx.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/UART/UART_tx.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/alu.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/alu_control.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/hdl/ascii.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/bus_interconnect.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/control_unit.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/data_memory.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/hdl/debouncer.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/decode.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/execute.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/fetch.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/hazard_control_unit.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/hazard_forwarding_unit.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/imm_gen.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/new/instruction_assembler.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/memory_access.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/new/mnemonic_decoder.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/new/operand_interpreter.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/register_file.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/new/tokenizer.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/write_back.v
  C:/Users/30697/OneDrive/project_writng/project_writng.srcs/sources_1/imports/src/top_unit_pipelined.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/30697/OneDrive/project_writng/project_writng.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/30697/OneDrive/project_writng/project_writng.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_unit_pipelined -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_unit_pipelined.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_unit_pipelined_utilization_synth.rpt -pb top_unit_pipelined_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
